### ISSUE TITLE
Not exactly sure how to explain 

### ISSUE THREAD

**Issue by UnPurgable** [didlly/grank#5] opened 2022-01-26 03:37 UTC
![image](https://user-images.githubusercontent.com/81527528/151099998-42bb69a5-50c2-4f0c-808e-122665d1ca27.png)

**Comment by didlly** [comment] 2022-01-26 18:20
Hi @UnPurgable,

Okay, so I think what happened is the program assumed the message from Dank Memer contained the number, however it was actually a ```cooldown``` message. It then tried to access a list index that was not present. This bug should be fixed in [this](https://github.com/didlly/grank/commit/2dcf55a857f06ea62cc87002fcebe0e17a2c02a2) commit (I accidentally pushed an update which made the cooldown system make the cooldown too short).

**Comment by didlly** [comment] 2022-01-29 16:11
I have just realized that the issue is not entirely fixed. I will fix it in a later commit.

**Comment by UnPurgable** [comment] 2022-01-29 22:47
aight, also can you please make a "guilded" account or add me on discord? (UnPurgable#6969) i have some questions and communicating via github is insanely hard.

**Comment by didlly** [comment] 2022-01-30 10:37
Fixed in [this](https://github.com/didlly/grank/commit/30329be30dac9d325c428f599fc27e7e03ca7f39) commit and [this](https://github.com/didlly/grank/commit/b9f82632ee322ada238eaa3d48754eedc8e811d5) commit.

**Closed by didlly** 2022-01-30 10:37 UTC
Labels: bug
